### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by AnnaBowatt** [ApryseSDK/pdftron-go#24]
When i try to build or run my go application i get this error 

```
imports github.com/pdftron/pdftron-go/v2: build constraints exclude all Go files in C:\GoPath\pkg\mod\github.com\pdftron\pdftron-go\v2@v2.3.1
```

i get the same error when using wsl as well 

```
package bowatt.com
        imports github.com/pdftron/pdftron-go/v2: build constraints exclude all
Go files in /home/anna/go/pkg/mod/github.com/pdftron/pdftron-go/v2@v2.3.1
```

my go mod looks like this 

```
module program
go 1.22.5

require (
	...
	github.com/pdftron/pdftron-go/v2 v2.3.1
	...
)

```

i've tried specifying the build tag but there is no change. i even downloaded the repo and updated the files to use 1.18+ build tags and still the same error

**Comment by AnnaBowatt** [comment]
Think i found a fix, if you are on a modern version of go you will need to set `CGO_ENABLED=1`

**Comment by Light-C** [comment]
> I Think I found a fix, if you are on a modern version of Go you will need to set `CGO_ENABLED=1`

Hello， I have the same problem,  how do you fix it?

**Comment by AnnaBowatt** [comment]
i set the environmental variable `CGO_ENABLED` to `1`
